/**
 * Client build: bundle the TypeScript, emit content-hashed assets, and stamp the
 * runtime config.
 *
 * Output layout (this is what `outputDirectory` points at on Vercel):
 *
 *   public/index.html               no-cache; references the hashed assets
 *   public/config.js                no-cache; PUBLIC_WS_URL and build id
 *   public/assets/app.<hash>.js     immutable
 *   public/assets/style.<hash>.css  immutable
 *
 * Hashing the filenames (rather than adding a query string) is what makes the
 * `immutable` cache header in vercel.json safe.
 */

import { createHash } from 'node:crypto';
import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import * as esbuild from 'esbuild';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const clientDir = join(root, 'client');
const outDir = join(root, 'public');
const assetsDir = join(outDir, 'assets');

const watch = process.argv.includes('--watch');
const dev = watch || process.env.NODE_ENV === 'development';

/** 10 hex chars of sha256 — plenty to distinguish builds. */
function hash(content) {
  return createHash('sha256').update(content).digest('hex').slice(0, 10);
}

export async function buildClient({ log = true } = {}) {
  await rm(assetsDir, { recursive: true, force: true });
  await mkdir(assetsDir, { recursive: true });

  const result = await esbuild.build({
    entryPoints: [join(clientDir, 'main.ts')],
    bundle: true,
    // `write: false` still needs an outdir so esbuild can name its outputs.
    outdir: assetsDir,
    format: 'esm',
    // Baseline that covers every browser with Pointer Events + OffscreenCanvas.
    target: ['es2020', 'chrome90', 'firefox90', 'safari15'],
    platform: 'browser',
    minify: !dev,
    sourcemap: true,
    legalComments: 'none',
    write: false,
    metafile: true,
    define: { 'process.env.NODE_ENV': JSON.stringify(dev ? 'development' : 'production') },
    logLevel: 'silent',
  });

  const jsFile = result.outputFiles.find((f) => f.path.endsWith('.js'));
  const mapFile = result.outputFiles.find((f) => f.path.endsWith('.js.map'));
  if (jsFile === undefined) throw new Error('esbuild produced no JS output');

  const jsHash = hash(jsFile.contents);
  const jsName = `app.${jsHash}.js`;
  // Point the bundle at its hashed sourcemap name.
  const jsText = jsFile.text.replace(/\/\/# sourceMappingURL=.*$/m, `//# sourceMappingURL=${jsName}.map`);
  await writeFile(join(assetsDir, jsName), jsText);
  if (mapFile !== undefined) await writeFile(join(assetsDir, `${jsName}.map`), mapFile.text);

  const css = await readFile(join(clientDir, 'style.css'), 'utf8');
  const cssName = `style.${hash(css)}.css`;
  await writeFile(join(assetsDir, cssName), css);

  const html = (await readFile(join(clientDir, 'index.html'), 'utf8'))
    .replace('href="style.css"', `href="assets/${cssName}"`)
    .replace('src="app.js"', `src="assets/${jsName}"`);
  if (html.includes('href="style.css"') || html.includes('src="app.js"')) {
    throw new Error('index.html asset references did not get rewritten');
  }
  await writeFile(join(outDir, 'index.html'), html);

  const buildId = `${new Date().toISOString().replace(/\.\d+Z$/, 'Z')}-${jsHash}`;
  const wsUrl = (process.env.PUBLIC_WS_URL ?? '').trim();
  if (wsUrl.length > 0 && !/^wss?:\/\//.test(wsUrl)) {
    throw new Error(`PUBLIC_WS_URL must start with ws:// or wss:// (got "${wsUrl}")`);
  }
  await writeFile(
    join(outDir, 'config.js'),
    `/* generated by scripts/build-client.mjs — do not edit */\n` +
      `window.CANVAS_CONFIG = ${JSON.stringify({ wsUrl: wsUrl.length > 0 ? wsUrl : null, build: buildId })};\n`,
  );

  const bytes = Buffer.byteLength(jsText);
  if (log) {
    console.log(`  client  assets/${jsName}  ${(bytes / 1024).toFixed(1)} kB${dev ? ' (dev, unminified)' : ''}`);
    console.log(`  client  assets/${cssName}  ${(css.length / 1024).toFixed(1)} kB`);
    console.log(`  client  config.js  wsUrl=${wsUrl.length > 0 ? wsUrl : '(derive from page origin)'}`);
  }
  return { jsName, cssName, buildId, bytes };
}

if (watch) {
  await buildClient();
  console.log('  client  watching for changes…');
  const { watch: fsWatch } = await import('node:fs');
  let timer = null;
  fsWatch(clientDir, { recursive: true }, () => {
    if (timer !== null) clearTimeout(timer);
    timer = setTimeout(() => {
      buildClient({ log: false })
        .then((r) => console.log(`  client  rebuilt ${r.jsName}`))
        .catch((err) => console.error(`  client  build failed: ${err.message}`));
    }, 80);
  });
} else if (import.meta.url === `file://${process.argv[1]}`) {
  await buildClient();
}
